import type { Battle, CatalogBattle } from './types'

export const catalog: CatalogBattle[] = [
  { title: 'Waterloo', year: '1815', category: 'Historical', location: 'Waterloo, Belgium', available: true },
  { title: 'Gettysburg', year: '1863', category: 'Historical', location: 'Pennsylvania, USA', available: false },
  { title: 'Hastings', year: '1066', category: 'Historical', location: 'East Sussex, England', available: false },
  { title: 'Midway', year: '1942', category: 'Historical', location: 'Central Pacific', available: false },
  { title: "Helm's Deep", year: 'T.A. 3019', category: 'Fantasy', location: 'Rohan', available: false },
  { title: 'Pelennor Fields', year: 'T.A. 3019', category: 'Fantasy', location: 'Gondor', available: false },
  { title: 'Blackwater', year: '299 AC', category: 'Fantasy', location: "King's Landing", available: false },
  { title: 'Hoth', year: '3 ABY', category: 'Science Fiction', location: 'Outer Rim', available: false },
  { title: 'Reach', year: '2552', category: 'Science Fiction', location: 'Epsilon Eridani', available: false },
  { title: 'Siege of Terra', year: 'M31', category: 'Science Fiction', location: 'Sol System', available: false },
]

export const waterloo: Battle = {
  id: 'waterloo',
  title: 'The Battle of Waterloo',
  location: 'Waterloo, United Kingdom of the Netherlands',
  date: '18 June 1815',
  duration: '11:30 — 20:30',
  summary:
    "Napoleon's final campaign ended on the rain-soaked fields south of Waterloo, where Wellington's coalition held long enough for Blücher's Prussian army to arrive.",
  outcome: 'Decisive Coalition victory',
  forces: 'Coalition 118,000 · French 73,000',
  casualties: 'Coalition 22,000 · French 33,000',
  commanders: [
    { name: 'Arthur Wellesley', role: 'Duke of Wellington', side: 'allied', monogram: 'W' },
    { name: 'Napoleon Bonaparte', role: 'Emperor of the French', side: 'french', monogram: 'N' },
    { name: 'Gebhard von Blücher', role: 'Prussian Field Marshal', side: 'allied', monogram: 'B' },
  ],
  units: [
    {
      id: 'anglo-center',
      name: "Wellington's Center",
      side: 'allied',
      strength: '32,000',
      path: [
        { at: 0, x: 47, y: 31 },
        { at: 45, x: 47, y: 32 },
        { at: 78, x: 49, y: 33 },
        { at: 100, x: 49, y: 37 },
      ],
    },
    {
      id: 'hougoumont',
      name: 'Hougoumont Garrison',
      side: 'allied',
      strength: '2,500',
      path: [
        { at: 0, x: 29, y: 48 },
        { at: 100, x: 29, y: 48 },
      ],
    },
    {
      id: 'derlon',
      name: "d'Erlon's I Corps",
      side: 'french',
      strength: '20,000',
      path: [
        { at: 0, x: 57, y: 75 },
        { at: 28, x: 56, y: 65 },
        { at: 43, x: 56, y: 49 },
        { at: 55, x: 60, y: 61 },
        { at: 100, x: 63, y: 72 },
      ],
    },
    {
      id: 'ney-cavalry',
      name: "Ney's Cavalry",
      side: 'french',
      strength: '9,000',
      path: [
        { at: 0, x: 43, y: 73 },
        { at: 48, x: 42, y: 68 },
        { at: 63, x: 43, y: 43 },
        { at: 76, x: 47, y: 60 },
        { at: 100, x: 47, y: 72 },
      ],
    },
    {
      id: 'prussians',
      name: "Blücher's Prussians",
      side: 'allied',
      strength: '48,000',
      path: [
        { at: 0, x: 97, y: 76 },
        { at: 56, x: 92, y: 69 },
        { at: 72, x: 79, y: 64 },
        { at: 88, x: 68, y: 60 },
        { at: 100, x: 60, y: 61 },
      ],
    },
    {
      id: 'guard',
      name: 'Imperial Guard',
      side: 'french',
      strength: '8,000',
      path: [
        { at: 0, x: 48, y: 83 },
        { at: 75, x: 48, y: 80 },
        { at: 89, x: 48, y: 47 },
        { at: 100, x: 48, y: 77 },
      ],
    },
  ],
  events: [
    {
      id: 'hougoumont-attack',
      at: 8,
      time: '11:30',
      title: 'Assault on Hougoumont',
      description: 'French infantry attacks the fortified château, beginning a battle within the battle that will last all day.',
      position: { x: 29, y: 48 },
    },
    {
      id: 'grand-battery',
      at: 25,
      time: '13:00',
      title: 'The Grand Battery opens fire',
      description: "Eighty guns begin a massive bombardment of Wellington's center before d'Erlon's advance.",
      position: { x: 51, y: 63 },
    },
    {
      id: 'derlon-attack',
      at: 38,
      time: '13:30',
      title: "d'Erlon's corps advances",
      description: 'Four French divisions climb the muddy slope toward the exposed Allied left-center.',
      position: { x: 57, y: 48 },
    },
    {
      id: 'cavalry-charge',
      at: 57,
      time: '16:00',
      title: "Ney's massed cavalry charge",
      description: 'Thousands of cuirassiers crest the ridge, finding the Allied infantry formed into defensive squares.',
      position: { x: 43, y: 42 },
    },
    {
      id: 'prussian-arrival',
      at: 72,
      time: '16:30',
      title: 'The Prussians arrive',
      description: "Bülow's IV Corps strikes Napoleon's right flank at Plancenoit, forcing him to divide his reserves.",
      position: { x: 77, y: 64 },
    },
    {
      id: 'guard-advance',
      at: 88,
      time: '19:30',
      title: 'The Imperial Guard advances',
      description: "Napoleon commits his last reserve. The Guard climbs toward Wellington's line through smoke and artillery fire.",
      position: { x: 49, y: 45 },
    },
    {
      id: 'rout',
      at: 97,
      time: '20:15',
      title: 'The French army breaks',
      description: 'The Guard recoils. Wellington signals a general advance as the Prussians close from the east.',
      position: { x: 52, y: 57 },
    },
  ],
}
